/// GET /client-login/
///
/// Auto-login from a one-time token generated by POST /api2/client-login/.
/// The sync client opens the browser to this URL with the token and
/// the user gets automatically logged in.
use axum::{
    extract::{Query, State},
    http::{HeaderMap, StatusCode},
    response::{IntoResponse, Redirect},
};
use sea_orm::{ActiveModelTrait, ColumnTrait, EntityTrait, ModelTrait, QueryFilter, Set};
use std::collections::HashMap;
use std::sync::Arc;

use crate::AppState;
use crate::auth::token::generate_api_token;
use crate::entity::{client_login_token, user};
use crate::error::AppError;

const TOKEN_TTL_SECS: i64 = 30;

pub async fn client_token_login(
    State(state): State<Arc<AppState>>,
    Query(params): Query<HashMap<String, String>>,
) -> Result<impl IntoResponse, AppError> {
    let db = state.db.as_ref();

    let token_str = match params.get("token") {
        Some(t) if t.len() == 32 => t,
        _ => {
            return Ok(Redirect::to("/libraries/").into_response());
        }
    };

    // Look up the token
    let record = client_login_token::Entity::find()
        .filter(client_login_token::Column::Token.eq(token_str))
        .one(db)
        .await
        .map_err(|_| AppError::internal("database error"))?;

    let record = match record {
        Some(r) => r,
        None => {
            let next = resolve_next(params.get("next").map(String::as_str));
            return Ok(Redirect::to(&next).into_response());
        }
    };

    // Check 30-second expiry
    let now = chrono::Utc::now().timestamp();
    let elapsed = now - record.created_at;
    if !(0..=TOKEN_TTL_SECS).contains(&elapsed) {
        let _ = record.delete(db).await;
        let next = resolve_next(params.get("next").map(String::as_str));
        return Ok(Redirect::to(&next).into_response());
    }

    // Token is valid — get the username before deleting
    let username = record.username.clone();

    // Delete the token (one-time use)
    let _ = record.delete(db).await;

    // Look up the user
    let user_record = user::Entity::find()
        .filter(user::Column::Email.eq(&username))
        .one(db)
        .await
        .map_err(|_| AppError::internal("database error"))?;

    let user_record = match user_record {
        Some(u) if u.is_active => u,
        _ => {
            let next = resolve_next(params.get("next").map(String::as_str));
            return Ok(Redirect::to(&next).into_response());
        }
    };

    // Generate a new session token
    let api_token = generate_api_token();
    let ttl_days = state.config.auth.api_token_ttl_days;
    let expires_at = now + (ttl_days as i64 * 86400);

    let token_record = crate::entity::api_token::ActiveModel {
        id: sea_orm::NotSet,
        user_id: Set(user_record.id),
        token: Set(api_token.clone()),
        created_at: Set(now),
        expires_at: Set(Some(expires_at)),
        device_id: Set(None),
        platform: Set(None),
        device_name: Set(None),
        client_version: Set(None),
    };

    token_record
        .insert(db)
        .await
        .map_err(|e| AppError::internal(format!("failed to create session token: {e}")))?;

    let secure = if state.config.server.site_url.starts_with("https") {
        "; Secure"
    } else {
        ""
    };
    let cookie = format!(
        "seahub-session={}; HttpOnly; SameSite=Lax; Path=/; Max-Age={}{}",
        api_token,
        ttl_days * 86400,
        secure,
    );

    let next = resolve_next(params.get("next").map(String::as_str));

    let csrf_cookie = crate::auth::csrf::csrf_cookie_header(
        &state.csrf_secret,
        &api_token,
        state.config.server.secure_cookies(),
        Some(ttl_days * 86400),
    );

    let mut resp_headers = HeaderMap::new();
    resp_headers.insert(
        axum::http::header::LOCATION,
        axum::http::HeaderValue::from_str(&next)
            .map_err(|_| AppError::internal("Failed to create location header"))?,
    );
    resp_headers.append(
        axum::http::header::SET_COOKIE,
        cookie
            .parse::<axum::http::HeaderValue>()
            .map_err(|_| AppError::internal("Failed to create session cookie header"))?,
    );
    resp_headers.append(
        axum::http::header::SET_COOKIE,
        csrf_cookie
            .parse::<axum::http::HeaderValue>()
            .map_err(|_| AppError::internal("Failed to create CSRF cookie header"))?,
    );

    let response = (StatusCode::FOUND, resp_headers).into_response();

    Ok(response)
}

/// Resolve the `next` URL to redirect to.
/// Falls back to /libraries/ for invalid or unsafe URLs.
fn resolve_next(next: Option<&str>) -> String {
    const SAFE_PREFIXES: &[&str] = &["/libraries/", "/shares/", "/settings/", "/search/"];

    match next {
        Some(url) if url.starts_with('/') => {
            if SAFE_PREFIXES.iter().any(|p| url.starts_with(p)) {
                url.to_string()
            } else {
                "/libraries/".to_string()
            }
        }
        _ => "/libraries/".to_string(),
    }
}
